#!/usr/bin/env bash
set -euo pipefail

# Install Go on Linux and configure environment variables.
# Supports: amd64, arm64.
#
# Optional env vars:
#   GO_VERSION=1.24.2
#   INSTALL_DIR=/usr/local
#   GOPATH_DIR=$HOME/go
#
# Usage:
#   chmod +x install-go-env-linux.sh
#   ./install-go-env-linux.sh
#
# If not run as root, the script uses sudo where required.

GO_VERSION="${GO_VERSION:-1.24.2}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local}"
GOPATH_DIR="${GOPATH_DIR:-$HOME/go}"
PROFILE_D_FILE="/etc/profile.d/go_env.sh"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1"
    exit 1
  }
}

as_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

arch="$(uname -m)"
case "$arch" in
  x86_64|amd64)
    go_arch="amd64"
    ;;
  aarch64|arm64)
    go_arch="arm64"
    ;;
  *)
    echo "Unsupported CPU architecture: $arch"
    echo "Supported: x86_64/amd64, aarch64/arm64"
    exit 1
    ;;
esac

need_cmd curl
need_cmd tar
need_cmd uname
need_cmd mktemp
need_cmd grep

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

tarball="go${GO_VERSION}.linux-${go_arch}.tar.gz"
url="https://go.dev/dl/${tarball}"

echo "Downloading $url"
curl -fL "$url" -o "$tmp_dir/$tarball"

echo "Installing Go $GO_VERSION to $INSTALL_DIR/go"
as_root rm -rf "$INSTALL_DIR/go"
as_root tar -C "$INSTALL_DIR" -xzf "$tmp_dir/$tarball"

echo "Configuring global profile in $PROFILE_D_FILE"
as_root tee "$PROFILE_D_FILE" >/dev/null <<EOF
# Generated by install-go-env-linux.sh
export GOROOT=${INSTALL_DIR}/go
export GOPATH=${GOPATH_DIR}
export PATH=\$PATH:\$GOROOT/bin:\$GOPATH/bin
EOF

# Ensure user's shell picks up values quickly (idempotent append).
user_rc="${HOME}/.profile"
if [[ -f "${HOME}/.zshrc" ]]; then
  user_rc="${HOME}/.zshrc"
fi

marker="# Added by install-go-env-linux.sh"
if ! grep -qF "$marker" "$user_rc" 2>/dev/null; then
  cat >>"$user_rc" <<EOF

$marker
export GOROOT=${INSTALL_DIR}/go
export GOPATH=${GOPATH_DIR}
export PATH=\$PATH:\$GOROOT/bin:\$GOPATH/bin
EOF
fi

mkdir -p "$GOPATH_DIR" "$GOPATH_DIR/bin" "$GOPATH_DIR/pkg" "$GOPATH_DIR/src"

# Load environment for this script run.
export GOROOT="${INSTALL_DIR}/go"
export GOPATH="${GOPATH_DIR}"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

echo "Verifying installation..."
go version

echo
echo "Go installation complete."
echo "Current shell:"
echo "  GOROOT=$GOROOT"
echo "  GOPATH=$GOPATH"
echo "  go binary: $(command -v go)"
echo
echo "Open a new shell or run: source $user_rc"
