#!/usr/bin/env bash
set -euo pipefail

# Install and configure beanstalkd on Ubuntu for small Oracle Cloud VMs.
# Tuned defaults are conservative for 1 vCPU / 1 GB RAM instances.
#
# Optional env vars:
#   LISTEN_ADDR=127.0.0.1     # Set to 0.0.0.0 only if you need remote access.
#   LISTEN_PORT=11300
#   MAX_JOB_SIZE=65535        # bytes
#   SERVICE_MEMORY_MAX=256M   # systemd hard limit for service memory
#
# Example:
#   sudo LISTEN_ADDR=0.0.0.0 SERVICE_MEMORY_MAX=384M ./install-beanstalkd-oracle-ubuntu.sh

LISTEN_ADDR="${LISTEN_ADDR:-127.0.0.1}"
LISTEN_PORT="${LISTEN_PORT:-11300}"
MAX_JOB_SIZE="${MAX_JOB_SIZE:-65535}"
SERVICE_MEMORY_MAX="${SERVICE_MEMORY_MAX:-256M}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Please run as root (use sudo)."
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "[1/6] Updating package index..."
apt-get update -y

echo "[2/6] Installing beanstalkd..."
apt-get install -y --no-install-recommends beanstalkd

echo "[3/6] Configuring beanstalkd defaults..."
if [[ -f /etc/default/beanstalkd && ! -f /etc/default/beanstalkd.bak ]]; then
  cp /etc/default/beanstalkd /etc/default/beanstalkd.bak
fi

cat >/etc/default/beanstalkd <<EOF
# Generated by install-beanstalkd-oracle-ubuntu.sh
START=yes
BEANSTALKD_LISTEN_ADDR=${LISTEN_ADDR}
BEANSTALKD_LISTEN_PORT=${LISTEN_PORT}
BEANSTALKD_MAX_JOB_SIZE=${MAX_JOB_SIZE}
EOF

echo "[4/6] Applying lightweight systemd limits for small VM..."
mkdir -p /etc/systemd/system/beanstalkd.service.d
cat >/etc/systemd/system/beanstalkd.service.d/limits.conf <<EOF
[Service]
MemoryMax=${SERVICE_MEMORY_MAX}
TasksMax=128
NoNewPrivileges=true
EOF

echo "[5/6] Enabling and restarting service..."
systemctl daemon-reload
systemctl enable beanstalkd
systemctl restart beanstalkd

echo "[6/6] Verifying service status..."
systemctl --no-pager --full status beanstalkd | sed -n '1,15p'

echo
echo "Beanstalkd is installed."
echo "Listening on ${LISTEN_ADDR}:${LISTEN_PORT}"
echo "If LISTEN_ADDR=127.0.0.1, expose it via SSH tunnel or a private network only."
